
version: 2

sources:
  - name: snowball
    schema: PUBLIC
    database: SNOWBALL
    tables:
      - name: SNOWBALL_INVOICES

models:
    - name: scaffold
      description: "Monthly scaffold between start/end invoice date"
      
    - name: customer_revenue_sb
      description: "Rest of model"
      columns:
      - name: customer_id
        description: Primary key
        tests:
          - not_null
      
