
version: 2

sources:
  - name: snowball
    database: SNOWBALL
    schema: '|
      {%- if  target.name == "test" -%} TEST
      {%- elif target.name == "prod"  -%} PROD
      {%- else -%} invalid_database
      {%- endif -%}'

models:
    - name: t_scaffold
      description: "Monthly scaffold between start/end invoice date"
      
    - name: fct_customer_revenue_sb
      description: "Rest of model"
      columns:
      - name: customer_id
        description: Primary key
        tests:
          - not_null
      
